### ISSUE TITLE
Command not found bug

### ISSUE THREAD

**Issue by StervWasTaken** [Stervsera/Star-Js#1]
Working on fixing this bug

**Comment by Rstar284** [comment]
...And how can i get my bot to do the same thing?

**Comment by StervWasTaken** [comment]
Kinda fixing it

**Comment by Rstar284** [comment]
@Stervsera  Bug fixed yet??

**Comment by Rstar284** [comment]
Stervvvvvvvvvvvvvvvvvvvvvvvvvvvvv

**Comment by Rstar284** [comment]
i closing issue >:(

**Comment by StervWasTaken** [comment]
Dont close this its still open

**Comment by Rstar284** [comment]
then what is the issue!!!!!!!!!!!!!!!!!!!!!

**Comment by StervWasTaken** [comment]
Eee fixed
